---

apiVersion: v1
kind: Secret
metadata:
    name: cloud-sql-password
type: Opaque
data:
    password: S3ViZXJuZXRlc1JvY2tzIQ==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: default
data:
  READ_TIMEOUT_SECONDS: "15"
  WRITE_TIMEOUT_SECONDS: "15"
  NAME: "elithrar"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-deployment
  labels:
    app: kubernetes-spring
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-spring
      tier: frontend
  template:
    metadata:
      labels:
        app: kubernetes-spring
        tier: frontend
    spec:
      containers:
      - name: kub-demo
        image: gcr.io/fir-check-fdbf8/kubernetes-demo:v1
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
            valueFrom:
            secretKeyRef:
                name: cloud-sql-password
                key: password
        envFrom:
        - configMapRef:
            name: demo-config

---

apiVersion: v1
kind: Service
metadata:
  name: kub-deployment
  labels:
    app: kubernetes-spring
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubernetes-spring
    tier: frontend

---
